# -*- coding: utf-8 -*-
"""tugas 14 PCD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MBZL1_Bgqx7hO_7x6xwssmbi1PsqP3k8
"""

!pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt

#rentang 
temperature = np.arange(24, 26, 1) #'temperature
humidity = np.arange(77, 83, 1) #humidity
windSpeed = np.arange(0, 3, 1) #windSpeed
rainFall = np.arange(4, 7, 1) #rainFall

#values of temperature
temperature_verylow = fuzz.trimf(temperature, [24.74, 24.94, 25.15])
temperature_low = fuzz.trimf(temperature, [24.94, 25.14, 25.14])
temperature_medium = fuzz.trimf(temperature, [25.14, 25.34, 25.53])
temperature_high = fuzz.trimf(temperature, [25.34, 25.53, 25.73])
temperature_veryhigh = fuzz.trimf(temperature, [25.53, 25.70, 25.90])

#values of humidity
humidity_verylow = fuzz.trimf(humidity, [77.55, 78.41, 79.27])
humidity_low = fuzz.trimf(humidity, [78.41, 79.26, 80.13])
humidity_medium = fuzz.trimf(humidity, [79.26, 80.13, 80.99])
humidity_high = fuzz.trimf(humidity, [80.13, 80.85, 80.99])
humidity_veryhigh = fuzz.trimf(humidity, [80.99, 81.85, 82.72])

#values of windspeed
windSpeed_veryLow = fuzz.trimf(windSpeed, [0.09, 0.50, 0.91])
windSpeed_low = fuzz.trimf(windSpeed, [0.50, 0.91, 1.32])
windSpeed_medium = fuzz.trimf(windSpeed, [0.91, 1.32, 1.73])
windSpeed_high = fuzz.trimf(windSpeed, [1.13, 1.73, 2.14])
windSpeed_veryHigh = fuzz.trimf(windSpeed, [1.73, 2.14, 2.55])

#values of rainfall
rainFall_veryLow = fuzz.trimf(rainFall, [4.48, 5.14, 5.25])
rainFall_low = fuzz.trimf(rainFall, [5.18, 5.56, 5.86])
rainFall_medium = fuzz.trimf(rainFall, [5.5, 5.87, 6.22])
rainFall_high = fuzz.trimf(rainFall, [5.89, 6.23, 6.62])
rainFall_veryHigh = fuzz.trimf(rainFall, [6.25, 6.6, 6.9])

#visualisasi

fig, (ax0, ax1, ax2, ax3) = plt.subplots(nrows=4, figsize=(9,16))
ax0.plot(temperature, temperature_verylow, 'r', linewidth=1.5, label='VL')
ax0.plot(temperature, temperature_low, 'g', linewidth=1.5, label='L')
ax0.plot(temperature, temperature_medium, 'b', linewidth=1.5, label='M')
ax0.plot(temperature, temperature_high, 'r', linewidth=1, label='H')
ax0.plot(temperature, temperature_veryhigh, 'g', linewidth=1, label='VH')
ax0.set_title('temp')
ax0.legend()

ax1.plot(humidity, humidity_verylow, 'r', linewidth=1.5, label='VL')
ax1.plot(humidity, humidity_low, 'g', linewidth=1.5, label='L')
ax1.plot(humidity, humidity_medium, 'b', linewidth=1.5, label='M')
ax1.plot(humidity, humidity_high, 'r', linewidth=1, label='H')
ax1.plot(humidity, humidity_veryhigh, 'g', linewidth=1, label='VH')
ax1.set_title('humidity')
ax1.legend()

ax2.plot(windSpeed, windSpeed_veryLow, 'r', linewidth=1.5, label='VL')
ax2.plot(windSpeed, windSpeed_low, 'g', linewidth=1.5, label='L')
ax2.plot(windSpeed, windSpeed_medium, 'b', linewidth=1.5, label='M')
ax2.plot(windSpeed, windSpeed_high, 'r', linewidth=1, label='H')
ax2.plot(windSpeed, windSpeed_veryHigh, 'g', linewidth=1, label='VH')
ax2.set_title('windspeed')
ax2.legend()

ax3.plot(rainFall, rainFall_veryLow, 'r', linewidth=1.5, label='VL')
ax3.plot(rainFall, rainFall_low, 'g', linewidth=1.5, label='L')
ax3.plot(rainFall, rainFall_medium, 'b', linewidth=1.5, label='M')
ax3.plot(rainFall, rainFall_high, 'r', linewidth=1, label='H')
ax3.plot(rainFall, rainFall_veryHigh, 'g', linewidth=1, label='VH')
ax3.set_title('rainfall')
ax3.legend()

for ax in (ax0, ax1, ax2, ax3):
  ax.spines['top'].set_visible(False)
  ax.spines['right'].set_visible(False)
  ax.get_xaxis().tick_bottom()
  ax.get_yaxis().tick_left()
plt.tight_layout()

#fuzifikasi
temp_level_VL = fuzz.interp_membership(temperature, temperature_verylow, 60)
temp_level_L = fuzz.interp_membership(temperature, temperature_low, 60)
temp_level_M = fuzz.interp_membership(temperature, temperature_medium, 60)
temp_level_H = fuzz.interp_membership(temperature, temperature_high, 60)
temp_level_VH = fuzz.interp_membership(temperature, temperature_veryhigh, 60)

humi_level_VL = fuzz.interp_membership(humidity, humidity_verylow, 70)
humi_level_L = fuzz.interp_membership(humidity, humidity_low, 70)
humi_level_M = fuzz.interp_membership(humidity, humidity_medium, 70)
humi_level_H = fuzz.interp_membership(humidity, humidity_high, 70)
humi_level_VH = fuzz.interp_membership(humidity, humidity_veryhigh, 70)

wind_level_VL = fuzz.interp_membership(windSpeed, windSpeed_veryLow, 70)
wind_level_L = fuzz.interp_membership(windSpeed, windSpeed_low, 70)
wind_level_M = fuzz.interp_membership(windSpeed, windSpeed_medium, 70)
wind_level_H = fuzz.interp_membership(windSpeed, windSpeed_high, 70)
wind_level_VH = fuzz.interp_membership(windSpeed, windSpeed_veryHigh, 70)

rain_level_VL = fuzz.interp_membership(rainFall, rainFall_veryLow, 70)
rain_level_L = fuzz.interp_membership(rainFall, rainFall_low, 70)
rain_level_M = fuzz.interp_membership(rainFall, rainFall_medium, 70)
rain_level_H = fuzz.interp_membership(rainFall, rainFall_high, 70)
rain_level_VH = fuzz.interp_membership(rainFall, rainFall_veryHigh, 70)

rules1 = np.fmin(temp_level_VL, humi_level_VL)
rules2 = np.fmin(temp_level_L, humi_level_L)
rules3 = np.fmin(temp_level_M, humi_level_M)
rules4 = np.fmin(temp_level_H, humi_level_H)
rules5 = np.fmin(temp_level_VH, humi_level_VH)

wind_rules1 = np.fmin(rules1, wind_level_VL)
wind_rules2 = np.fmin(rules2, wind_level_L)
wind_rules3 = np.fmin(rules3, wind_level_M)
wind_rules4 = np.fmin(rules4, wind_level_H)
wind_rules5 = np.fmin(rules5, wind_level_VH)

rain_rules1 = np.fmin(wind_rules1, rain_level_VL)
rain_rules2 = np.fmin(wind_rules2, rain_level_L)
rain_rules3 = np.fmin(wind_rules3, rain_level_M)
rain_rules4 = np.fmin(wind_rules4, rain_level_H)
rain_rules5 = np.fmin(wind_rules5, rain_level_VH)
rain0 = np.zeros_like(rainFall)

#visualisasi output membership
fig, ax0 = plt.subplots(figsize=(8,3))
ax0.fill_between(rainFall, rain0, rain_rules1, facecolor='r', alpha=0.7)
ax0.plot(rainFall, rainFall_veryLow, 'r', linewidth=0.5, linestyle='--')
ax0.fill_between(rainFall, rain0, rain_rules2, facecolor='g', alpha=0.7)
ax0.plot(rainFall, rainFall_low, 'g', linewidth=0.5, linestyle='--')
ax0.fill_between(rainFall, rain0, rain_rules3, facecolor='b', alpha=0.7)
ax0.plot(rainFall, rainFall_medium, 'b', linewidth=0.5, linestyle='--')
ax0.fill_between(rainFall, rain0, rain_rules4, facecolor='r', alpha=0.7)
ax0.plot(rainFall, rainFall_high, 'r', linewidth=0.5, linestyle='--')
ax0.fill_between(rainFall, rain0, rain_rules5, facecolor='g', alpha=0.7)
ax0.plot(rainFall, rainFall_veryHigh, 'g', linewidth=0.5, linestyle='--')
ax0.set_title('output membership')

for ax in (ax0,):
  ax.spines['top'].set_visible(False)
  ax.spines['right'].set_visible(False)
  ax.get_xaxis().tick_bottom()
  ax.get_yaxis().tick_left()
plt.tight_layout()